### PR TITLE
Merge default and gpu modules

### LINKED ISSUE #12: Merge default and gpu instance modules
default_instance and gpu_instance modules look very similar.

I suggest merging them into one, leaving these as entrypoints populating required inputs.

cc @aaron-lane, @morgante

### PR DESCRIPTION
**Pull request by taylorludwig**
Fixes #12 

Creates a common `instance` submodule that can be used to greate `cpu` or `gpu` datalab instances. 

Changes `default` and `gpu` submodules to be simple wrappers around the new common `instance` submodule.

### CODE REVIEW

**Comment by taylorludwig** [comment]
@morgante one issue here is it'll require a migration - since old created resources from `default` or `gpu` modules are now moved down to the common module. 

We could either create a migration script. 

Or simply just suggest in a readme that people use the common `instance` submodule in-place of their original `default` or `gpu` ones. 

I've verified this with the example tests. 
Simply change  `source = "../../modules/gpu_instance"` to `source = "../../modules/instance"` (and for `gpu` implementations also set `gpu_instance = true`). Terraform plan/apply will show no changes needed since resources would be at the same level and have the same names.

**Comment by morgante** [comment]
@taylorludwig I don't think we need to use a full migration script, just add a small guide please (on how to replace with the common module in both cases).

**Comment by taylorludwig** [comment]
Sounds good @morgante 

If we are having users of the old modules migrate to use the new one, as well as suggesting new users use the new common module. 

Should we take the opportunity to either 

1. Delete the modules 
Or
2. At least note them as deprecated in the readmes 

As it is now `default`and `gpu` modules are simple wrappers around the common one with the only real difference being the value of parameter `gpu_instance`

**Comment by morgante** [comment]
I'd say we should:
- Delete the modules
- Add a note about migrating to the new approach in the CHANGELOG and README

**Comment by taylorludwig** [comment]
I've merged in the latest master changes. This is ready to go again

**Pull request merged**
