### PR TITLE
Enable secure boot for instance

### LINKED ISSUE #9: Enable secure boot if possible.
The secure boot is disabled for the shielded VM datalab instance is running on.  The documentation https://cloud.google.com/security/shielded-cloud/shielded-vm seems like there is not really a reson for not having the instance have enable_secure_bot as true.  I have tested launching a default datalab instance with my fork of the module, and it seems to work just fine, at least with the default datalab image.

```
  shielded_instance_config {
    enable_integrity_monitoring = true
    enable_secure_boot          = false
    enable_vtpm                 = true
  }
```
https://github.com/terraform-google-modules/terraform-google-datalab/blob/master/modules/default_instance/main.tf#L99

Can you please make the secure boot true, explain when and why it can't be set to true in which case maybe make it configurable via module variables.

### PR DESCRIPTION
**Pull request by SKozlovsky**
fix #9

### CODE REVIEW

**Comment by aaron-lane** [comment]
It turns out this is a breaking change. Existing VMs must be in the stopped state before secure boot can be enabled. Let's switch back to #15 and set the default to `false`.

**Comment by aaron-lane** [comment]
@SKozlovsky please revert to the variable approach and default the value to `false`.

**Comment by SKozlovsky** [comment]
> It turns out this is a breaking change. Existing VMs must be in the stopped state before secure boot can be enabled. Let's switch back to #15 and set the default to `false`.

@aaron-lane 
Maybe it isn't mandatory. I'll try to use the option `allow_stopping_for_update = true` to avoid a breaking change.

**Comment by SKozlovsky** [comment]
> @SKozlovsky please revert to the variable approach and default the value to `false`.

@aaron-lane 
unfortunately `allow_stopping_for_update = true` doesn't help

**Pull request closed without merging**
